Feature/concurrency
mycujoo/mls-ios pull request #1
Opened 2022-03-03 14:28 UTC by Ghararym

2022-03-04 14:28 UTC, MycujooMats requested changes
This PR is also missing code that updates the identityToken when a user signs out and back in. We can discuss this further if you have questions.

2022-03-04 14:28 UTC, MycujooMats commented on Sources/Core/App/Core/VideoPlayerImpl.swift
> +        event = nil
We don't have to call replaceCurrentItem or stop on the usecase, because those are already invoked when setting the event to nil

2022-03-04 14:28 UTC, MycujooMats commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +        static func welcome(with sessionId: String) -> String { "sessionId;" + sessionId }
The identityToken message is missing?

2022-03-04 14:28 UTC, MycujooMats commented on Sources/Core/Data/Repositories/EventRepositoryImpl.swift
> +            if [.started, .finished].contains(initialEvent?.status) {
This needs to be done differently, because what happens if the user continues to watch an upcoming screen until the event goes live? It wouldn't connect to the websocket currently, which it should.

2022-03-23 14:24 UTC, MycujooMats requested changes

2022-03-23 14:24 UTC, MycujooMats commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +                        let update: UpdateMessage = .concurrencyLimitReached(eventId: eventId, limit: Int(limitNumber) ?? 3)
Why are we changing back to reached? Exceeded is the correct terminology

2022-03-23 14:24 UTC, MycujooMats commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +                        debugPrint("### Websocket `badRequest` error: \(text)")
Can you only print this if the SDK user turned on verbose mode? The other websocket actually has an example of how this works (look at `printToConsole`)

2022-03-31 10:16 UTC, MycujooMats requested changes

2022-03-31 10:16 UTC, MycujooMats commented on Sources/Core/App/Core/MLS.swift
> +    public let useConcurrencyControl: Bool
Also, it might be better to put this on the PlayerConfig definition instead, so it can be changed more easily.

2022-03-31 10:16 UTC, MycujooMats commented on Sources/Core/App/Core/VideoPlayerImpl.swift
> +                        self.concurrencyLimitReachedCleanup(eventId: event.id, limit: limit)
Replace `Reached` with `Exceeded`

2022-03-31 10:16 UTC, MycujooMats commented on Sources/Core/App/Core/VideoPlayerImpl.swift
> +        let limitExceedView: UIView = {
Why is there a special view for this? And why does it look at screen size? We cannot make assumptions on how SDK users will layout the video, and what the size of the player will be.

Also, the default error message should just be the red text that we use for geoblocking and entitlement missing messages, so it does not need a separate view.

2022-03-31 10:16 UTC, MycujooMats commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +                        self.socket.disconnect()
I think this is missing a `canReconnect` set?

2022-03-31 10:16 UTC, MycujooMats commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +            DispatchQueue.main.asyncAfter(
Why on `main`?

2022-03-31 10:16 UTC, MycujooMats commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +                    self.retry(delay: delay, retry: retry, closure: closure)
I think this always retries, even after success?

2022-03-31 10:16 UTC, MycujooMats commented on Sources/Core/Data/Repositories/EventRepositoryImpl.swift
> +            if let useConcurrency = self?.useConcurrencyControl, useConcurrency {
Why `useConcurrency` and not `useConcurrencyControl`? Also, let's rename this to `enableConcurrencyControl` here, too.

2022-03-31 10:16 UTC, MycujooMats commented on Sources/Core/Data/Repositories/EventRepositoryImpl.swift
> +                            self?.stopEventUpdates(for: eventId)
This is also called by the VideoPlayerImpl when event is set to nil. I'd remove it from here.

2022-04-01 09:55 UTC, Ghararym commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +                    self.retry(delay: delay, retry: retry, closure: closure)
The log for retrying is this: 
`### Retrying... 0, delay: 0
### Retrying... 1, delay: 5
### Retrying... 2, delay: 10
### Retrying... 3, delay: 20
### Retrying... 4, delay: 40
### Retrying... 5, delay: 80`


but we can add a check for `!self.isConnected` to be sure this will retry only if it's not connected

2022-04-01 10:13 UTC, Ghararym commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +            DispatchQueue.main.asyncAfter(
moved to `global(qos: .background)`

2022-05-04 12:19 UTC, MycujooMats requested changes

2022-05-04 12:19 UTC, MycujooMats commented on Sources/Core/App/Core/MLS.swift
> +    public let enableConcurrencyControl: Bool
Why is this value still here? I think you moved `enableConcurrencyControl` to `PlayerConfig` (which I think is correct), so it shouldn't be here anymore, I believe.

2022-05-04 12:19 UTC, MycujooMats commented on Sources/Core/App/Core/VideoPlayerImpl.swift
> +        view?.infoTitleLabel.text = "Concurrency limit exceeded"
This needs to be localized

2022-05-04 12:19 UTC, MycujooMats commented on Sources/Core/App/Core/VideoPlayerImpl.swift
> +        view?.infoDescriptionLabel.text = "Concurrency limit of \(limit) has exceeded"
This needs to be localized

2022-05-04 12:19 UTC, MycujooMats commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +                    self.retry(delay: delay, retry: retry, closure: closure)
Two problems here now:
1. The retry function will still get called every time (it will just exit early). It's ok, but messy; it's better to have a cancelling mechanism.
2. The retryAttempt variable is never set back to 0 upon successful connection (which needs to happen for potential future issues with the connection)

2022-05-04 12:19 UTC, MycujooMats commented on Sources/Core/Data/Starscream/WebSocket.swift
> +        self.request.addValue(header, forHTTPHeaderField: "User-Agent")
This is not really the right place to put this. The reason for that is that these files were copied from the Starscream library because there was a pod conflict. In the future, we should remove these files and rely again on Cocoapods or SPM for pulling in this library, and so we shouldn't make custom changes directly to the library now.

Perhaps you can look into writing an extension that would continue to work even if we install Starscream properly. Otherwise, you might have to do a feature request with Starscream, or a PR on their repository.

2022-05-04 12:19 UTC, MycujooMats commented on Sources/Core/Data/UserAgentHeader.swift
> +public struct UserAgentHeader {
This should not be a public struct, it should be internal to do the Data "module" (I use quotations because it's a virtual module at the moment, not a real one)

2022-05-17 09:04 UTC, Ghararym commented on Sources/Core/Data/FeaturedWebsocketConnection.swift
> +                    self.retry(delay: delay, retry: retry, closure: closure)
`retryAttempt` is setting to 0 when socket is connected. `self.retryAttempt = .zero`

2022-05-25 09:00 UTC, MycujooMats approved these changes

2022-05-25 09:37 UTC, merged