Feature/in app purchase
mycujoo/mls-ios pull request #3
Opened 2022-08-22 08:41 UTC by Ghararym

2022-08-22 10:05 UTC, MycujooMats requested changes
Other comments:
- UseCases folder is defined in Xcode (in IAP section) but does not actually exist on the file system
- I saw you had a testPackageId variable in the code (presumably for your own testing). It's already been removed, but it still appears in git history. In this case it's not a sensitive identifier, but since this is a public repository I would still prefer not to have such identifiers committed to git.

2022-08-22 10:05 UTC, MycujooMats commented on Examples/iOS/WithInAppPurchaseAvailableViewController.swift
> +                    let paymentResult = try await paymentAPI.purchaseProduct(productId: product.id)
`paymentResult` is unhandled for now. Might be good to add a success handler (just a basic one that prints to the console)

2022-08-22 12:09 UTC, Ghararym commented on Sources/IAP/IAPIntegrationImpl.swift
> +                await result.transaction.finish()
A `Transaction` needs to be marked as `finished` whether it was successful or failed by Apple or our server. As if it doesn't, then every time user opens the app, the `listenForTransaction` method gets called and causes sending wrong info to the server. That's why it's marked as `finished` here.

2022-08-22 12:12 UTC, Ghararym commented on Sources/IAP/IAPIntegrationImpl.swift
> +            throw StoreException.jwsVerificationException
If I remember correctly, what we spoke with Igor, was that server would receive both messages. The chronological order doesn't make any difference. (Needs to be confirmed by @Igor)

2022-08-22 12:16 UTC, MycujooMats commented on Sources/IAP/IAPIntegrationImpl.swift
> +                await result.transaction.finish()
But how then do you indicate failure to the SDK user?

2022-08-22 12:16 UTC, MycujooMats commented on Sources/IAP/IAPIntegrationImpl.swift
> +            throw StoreException.jwsVerificationException
Ok, then let's leave this open until Igor is back to confirm

2022-08-22 13:39 UTC, Ghararym commented on Sources/IAP/IAPIntegrationImpl.swift
> +                await result.transaction.finish()
I modified the code so the SDK user will be notified about failure.

2022-08-22 15:37 UTC, Ghararym commented on Sources/Core/Domain/Repositories/MLSPaymentRepository.swift
> +    func listProductIds(eventId: String) async throws -> [String]
Actually the responsibility of this method is just to pass the eventId and retrieve the `apple_app_store_product_id` for the event. Then the `listProducts` usecase which is inside the IAP module, will pass those ids to Apple to retrieve the actual `Product`s. 
So I suggest keeping this naming here.

2022-08-22 15:50 UTC, MycujooMats commented on Sources/Core/Domain/Repositories/MLSPaymentRepository.swift
> +    func listProductIds(eventId: String) async throws -> [String]
I disagree, because you're assuming the repository knows what it's responsibility is, but that's why you have use-cases. Repositories are just interfaces to APIs, you do not build them for a specific purpose.

2022-08-22 15:55 UTC, MycujooMats commented on Sources/Core/App/Core/IAPIntegrataion.swift
> +public protocol IAPIntegration: AnyObject {
Also, the filename is misspelled

2022-08-22 15:57 UTC, Ghararym commented on Sources/Core/Domain/Repositories/MLSPaymentRepository.swift
> +    func listProductIds(eventId: String) async throws -> [String]
I disagree again as the method that the user will call is `listProducts`, which is a part of the IAP module. Which returns the Apple Products to the user.
Going into that method, it calls this method of `listProductIds` which is a use case inside the core module of SDK and returns only ids, so that method uses them to retrieve Apple's Products.

2022-08-23 11:43 UTC, Ghararym commented on Sources/IAP/IAPIntegrationImpl.swift
> +    init(paymentRepository: MLSPaymentRepository) {
Using use cases implemented for this.

2022-08-23 11:44 UTC, Ghararym commented on Sources/IAP/IAPIntegrationImpl.swift
> +        orderId = ""
removed this code.

2022-08-24 16:08 UTC, MycujooMats requested changes

2022-08-24 16:08 UTC, MycujooMats commented on Sources/Core/Domain/Entities/Public/EventPackages.swift
> +public struct EventPackages: Decodable {
Why is this plural? It represents a single object

2022-08-24 16:08 UTC, MycujooMats commented on Sources/Core/Domain/Repositories/MLSPaymentRepository.swift
> +    func listProducts(eventId: String) async throws -> EventPackages
This should be `[EventPackage]`

2022-08-24 16:08 UTC, MycujooMats commented on Sources/Core/Data/Repositories/MLSPaymentRepositoryImpl.swift
> +            _fetch(.listEventProducts(eventId: eventId), type: EventPackages.self) { eventPackages, error in
This would only work if the API response had a single object at the root, but it doesn't. It has an array of objects as a response, together with a cursor. To know how to do this, have a look at `EventRepositoryImpl` line `37`

2022-08-25 10:34 UTC, Ghararym commented on Sources/Core/Domain/Repositories/MLSPaymentRepository.swift
> +    func listProducts(eventId: String) async throws -> EventPackages
But the response that comes from the server includes pagination and an array of `packages`. 
So inside this struct,  So I think I only need to rename it from plural to singular.

2022-08-25 10:43 UTC, MycujooMats commented on Sources/Core/Domain/Repositories/MLSPaymentRepository.swift
> +    func listProducts(eventId: String) async throws -> EventPackages
Right, if you want to return the cursor as well (which is a fair point), then you should leave it as plural, because then this object is a wrapper for the array and the cursor. But then the other comment needs to be addressed.

2022-08-26 12:27 UTC, MycujooMats commented on Sources/IAP/IAPIntegrationImpl.swift
> +    func listProducts(eventId: String) async throws -> [(packageId: String, product: IAPProduct)] {
My suggestion was to rename everything to `package` instead of `product` if it's about the MCLS version of the object. So this should be `listPackages` (same applies elsewhere in the code)

2022-09-08 10:56 UTC, MycujooMats requested changes

2022-09-08 10:56 UTC, MycujooMats commented on Sources/Core/Data/API.swift
> +        case .paymentFulfillment(let contentType, let contentId):
I would call this `checkEntitlement`

2022-09-08 10:56 UTC, MycujooMats commented on Sources/Core/Data/Repositories/MLSPaymentRepositoryImpl.swift
> +    func fetchPurchaseFulfilled(order: Order) async throws -> Bool {
Here it's called purchaseFulfilled, but elsewhere it's called paymentFulfilled. I would suggest keeping naming like this consistent (although I suggested a different name altogether, `checkEntitlement`)

2022-09-08 10:56 UTC, MycujooMats commented on Sources/Core/Domain/Repositories/MLSPaymentRepository.swift
> +    func fetchPurchaseFulfilled(order: Order) async throws -> Bool
I do not think this should be on the public interface. Instead, `finishTransaction` should not return anything until the entitlement is created. So from the SDK user's perspective, the payment and the entitlement creation are the same step.

2022-09-23 13:23 UTC, merged